#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : osc-lib
Version  : 1.2.0
Release  : 6
URL      : http://pypi.debian.net/osc-lib/osc-lib-1.2.0.tar.gz
Source0  : http://pypi.debian.net/osc-lib/osc-lib-1.2.0.tar.gz
Summary  : OpenStackClient Library
Group    : Development/Tools
License  : Apache-2.0
Requires: osc-lib-python
Requires: Babel
Requires: cliff
Requires: keystoneauth1
Requires: os-client-config
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: simplejson
Requires: six
Requires: stevedore
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=======
osc-lib
=======
.. image:: https://img.shields.io/pypi/v/osc-lib.svg
:target: https://pypi.python.org/pypi/osc-lib/
:alt: Latest Version

%package python
Summary: python components for the osc-lib package.
Group: Default

%description python
python components for the osc-lib package.


%prep
%setup -q -n osc-lib-1.2.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489335904
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489335904
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
