#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : osc-lib
Version  : 2.2.0
Release  : 35
URL      : https://files.pythonhosted.org/packages/ad/71/ee714a1bc985f6153cf91941c1de9c7664d8d9527706344051e9f416f1e9/osc-lib-2.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/ad/71/ee714a1bc985f6153cf91941c1de9c7664d8d9527706344051e9f416f1e9/osc-lib-2.2.0.tar.gz
Summary  : OpenStackClient Library
Group    : Development/Tools
License  : Apache-2.0
Requires: osc-lib-license = %{version}-%{release}
Requires: osc-lib-python = %{version}-%{release}
Requires: osc-lib-python3 = %{version}-%{release}
Requires: cliff
Requires: keystoneauth1
Requires: openstacksdk
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: simplejson
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : cliff
BuildRequires : keystoneauth1
BuildRequires : openstacksdk
BuildRequires : oslo.i18n
BuildRequires : oslo.utils
BuildRequires : pbr
BuildRequires : simplejson
BuildRequires : stevedore

%description
osc-lib
        =======

%package license
Summary: license components for the osc-lib package.
Group: Default

%description license
license components for the osc-lib package.


%package python
Summary: python components for the osc-lib package.
Group: Default
Requires: osc-lib-python3 = %{version}-%{release}

%description python
python components for the osc-lib package.


%package python3
Summary: python3 components for the osc-lib package.
Group: Default
Requires: python3-core
Provides: pypi(osc_lib)
Requires: pypi(cliff)
Requires: pypi(keystoneauth1)
Requires: pypi(openstacksdk)
Requires: pypi(oslo.i18n)
Requires: pypi(oslo.utils)
Requires: pypi(pbr)
Requires: pypi(simplejson)
Requires: pypi(stevedore)

%description python3
python3 components for the osc-lib package.


%prep
%setup -q -n osc-lib-2.2.0
cd %{_builddir}/osc-lib-2.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592411167
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/osc-lib
cp %{_builddir}/osc-lib-2.2.0/LICENSE %{buildroot}/usr/share/package-licenses/osc-lib/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/osc-lib/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
